
#spring.datasource.url=jdbc:mysql://localhost/clients
#spring.datasource.hikari.username=root
#spring.datasource.hikari.password=
#spring.datasource.jdbcUrl=com.mysql.jdbc.Driver
#spring.data.jpa.repositories.enabled=true
#spring.jpa.hibernate.ddl-auto=update



spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/ass
        username: root
        password:
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
# --- server
server:
  port: 8081



